"""Add gppl_id to ApprovalMember

Revision ID: 0bff98b8ea79
Revises: 32881ba0a01e
Create Date: 2026-07-10 12:57:05.832966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bff98b8ea79'
down_revision = '32881ba0a01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gppl_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_members', schema=None) as batch_op:
        batch_op.drop_column('gppl_id')

    # ### end Alembic commands ###
