"""Initial migration

Revision ID: 32881ba0a01e
Revises: 
Create Date: 2026-07-10 12:18:46.817009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32881ba0a01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
